version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html  # Serve static files
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration (optional)
    ports:
      - "8080:80"  # Expose port 80 of Nginx container to port 8080 of the host
    networks:
      - app-network
    depends_on:
      - nodejs  # Wait for Node.js to be ready before starting Nginx

networks:
  app-network:
    driver: bridge
